### ISSUE TITLE
Peer-Programming-Code-Review

### ISSUE THREAD

**Issue by emarkees** [Jawad-Nazari/Capstone-Project#2]
Hello Jawad!!

You've done a great job!! 👍 👍  on your capstone! 
Your code is organized and easy to read. I like the transitions you've used for your menu, 
- I'd suggest other transitions in the about page.
-  a cursor pointer over the pictures of the "See the two last Web Development Bootcamps" section so it is more visually engaging. 

Excellent work on your JS code! Keep up the good work!  :)

Happy Coding 🥂 🥂

**Comment by emarkees** [comment]
@hafedefheij.  

Well done your code looks great , I have some notes II think it  may be it will be helpful
in index.js 
- The main function takes a count parameter but this parameter is never used in the function. Instead, the function always creates 6 speaker elements.

- The gridmaker function is called every time the body is clicked. This can cause performance issues as the function will be called frequently.

- The mainSpeakers element is being modified directly in the main function. It would be better to create a separate function to handle the styling of this element.

- The window.onload function is being used to call the main function. This means that the function will only be called once, when the page loads. It would be better to use an event listener that listens for changes to the window size, so that the layout can be adjusted dynamically.

Happy Coding 🥂 🥂

**Comment by Jawad-Nazari** [comment]
Hi @emarkees ,

Thanks for reviewing my code. Your recommendation will be considered and applied.
